services:
  app:
    image: todo-frontend-prod
    build:
      context: ./todo-frontend # The context will pick the given directory as the "build context".
      dockerfile: Dockerfile 
    volumes:
      - ./todo-frontend:/usr/src/app
    container_name: frontend-prod
  mongo:
    image: mongo
    # Map port on the host to port inside the container.
    ports:
      - "3456:27017"
    volumes:
      # Mounts a MongoDB initialization script.
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      # Persists MongoDB data by mapping a directory on the host to the MongoDB data directory inside the container.
      - ./todo-backend/mongo_data:/data/db
    container_name: mongo-prod
  redis:
    image: redis:latest
    ports:
      # Map port on the host to port inside the container.
      - "6379:6379"
    # Overwrites the default CMD to start Redis with append-only mode enabled (provides durability by logging every
    # write operation to disk.
    command: ['redis-server', '--appendonly', 'yes']
    # Persists Redis data by mapping a directory on the host to the Redis data directory inside the container.
    volumes:
      - ./todo-backend/redis_data:/data
    container_name: redis-prod
  server:
    image: todo-backend-prod
    build:
      context: ./todo-backend
      dockerfile: Dockerfile
    # Mounts the current directory on the host to the given directory inside the container. This allows for real-time 
    # code changes without rebuilding the container.
    volumes:
      - ./todo-backend:/usr/src/app
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017/${MONGO_DB}
    depends_on:
      - mongo
      - redis
    container_name: backend-prod
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mounts the Nginx configuration file.
    ports:
      - 8080:80 # Maps port 80 inside the container to port 8080 on the host.
    container_name: reverse-proxy-prod
    depends_on:
      - app
      - server