services:
  app:
    image: patientor-frontend
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8080/api
    volumes:
      - ./frontend:/usr/src/app
    container_name: patientor-frontend
  server:
    image: patientor-backend
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
    container_name: patientor-backend
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: patientor-reverse-proxy
    depends_on:
      - app
      - server
      
      